version: "3.9"
services:
  frontend:
    build:
      context: ./fronted
      dockerfile: DockerfileFrontendRPR
    container_name: frontendRPR
    ports:
      - "3110:3000"
    volumes:
      - ./fronted:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Activa polling para asegurar detección de cambios en Docker
    networks:
      - redwebRPR

  backend:
    build:
      context: ./backend
      dockerfile: DockerfileBackendRPR
    container_name: backendRPR
    command: bash -c "composer install && php -S 0.0.0.0:8000 -t public"
    ports:
      - "8110:8000"
    volumes:
      - ./backend:/app
    networks:
      - redwebRPR

  web:
    build:
      context: ./web
      dockerfile: DockerfileWebRPR
    container_name: webRPR
    ports:
      - "80:80" # si tienes problemas con el puerto 80 cambia el puerto externo aquí
    networks:
      - redwebRPR

networks:
  redwebRPR:
    driver: bridge